blank_issues_enabled: false
contact_links:
  - name: OSATE Mailing List
    url: https://groups.google.com/g/osate
    about: Please ask and answer questions about OSATE or analysis plugins on the mailing list.